name: DDD
description: Study on how to architecture a clean, tested, domain centered app.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.1
  equatable: ^1.2.5
  intl: ^0.16.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
